<div class="container">
	<table class="table table-striped">
	<thead>
		<tr>
			<th>Report Name</th>
			<th>View File</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->reports as $report) : ?>
		<tr>
			<td>
				<?php $url = $this->url('dog/report',['action' => 'view','uuid' => $report['UUID']]); ?>
				<a href="<?php echo $url; ?>" target="_blank"><?php echo $report['NAME']; ?></a>
			</td>
			<td><?php echo $report['VIEW']; ?></td>
			<td>
				<a href="<?php echo $this->url('dog/report', ['action' => 'update', 'uuid' => $report['UUID']]); ?>"><i class="fas fa-edit"></i></a>
				<a href="<?php echo $this->url('dog/report', ['action' => 'delete', 'uuid' => $report['UUID']]); ?>"><i class="fas fa-trash-alt"></i></a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
	<?php echo $this->paginationControl($this->reports, 'Sliding', '/dog/partial/paginator.phtml', ['count' => $this->count]) ?>
</div>