<div class="col">
<?php
echo $this->form()->openTag($form);
?>
	<div class="container">
		<div class="row">
			<div class="col">
				<h3><?php echo $this->title; ?></h3>
			</div>
			<div class="d-flex justify-content-end">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
		</div>
	</div>
	
	<!-- Hidden Elements -->
	<div class="form-group">
		<?php echo $this->formRow($form->get('SECURITY')); ?>
	</div>
	
	<div class="form-group">
		<?php echo $this->formRow($form->get('NAME')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('BREED')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('SEX')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('DATE_BIRTH')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('DATE_RABIESEXP')); ?>
	</div>

<?php echo $this->form()->closeTag($form); ?>
</div>