<div class="col-6">
<?php
echo $this->form()->openTag($form);
?>

	<h3><?php echo $this->title; ?></h3>
	
	<!-- Hidden Elements -->
	<div class="form-group">
		<?php echo $this->formRow($form->get('SECURITY')); ?>
	</div>
	
	<div class="form-group">
		<?php echo $this->formRow($form->get('NAME')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('BREED')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('SEX')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('DATE_BIRTH')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('DATE_RABIESEXP')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('SUBMIT')); ?>
	</div>

<?php echo $this->form()->closeTag($form); ?>
</div>