<div class="card mb-4">
	<div class="card-header d-flex justify-content-between">
		<div>
			<b>Dogs</b>
		</div>
		<div>
			<a href="<?php echo $this->url('dog/dog', ['action' => 'create']); ?>" class="btn btn-primary btn-rounded">Add</a>
		</div>
	</div>
	
	<div class="card-body">
        <table class="table table-striped">
        	<thead>
        		<tr>
        			<th>Dog Name</th>
        		</tr>
        	</thead>
        	<tbody>
        	<?php foreach ($this->dogs as $dog) : ?>
        		<tr>
        			<td><a href="<?php echo $this->url('dog/dog', ['action' => 'update','uuid' => $dog['UUID']]); ?>"><?=$dog['NAME']?></a></td>
        		</tr>
    		<?php endforeach; ?>
        	</tbody>
        </table>
    </div>
</div>