<div class="col">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Dogs</h3>
			</div>
			<div class="d-flex justify-content-end">
<!-- 				<a href="" class="btn btn-primary btn-rounded mb-4" data-toggle="modal" data-target="#modalDogUsersForm">Assign Owner</a> -->
				<a href="<?php echo $this->url('dog/dog', ['action' => 'create']); ?>" class="btn btn-primary btn-rounded mb-4">Add</a>
			</div>
		</div>
	</div>
	
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>Dog Name</th>
    		</tr>
    	</thead>
    	<tbody>
    	<?php foreach ($this->dogs as $dog) : ?>
    		<tr>
    			<td><a href="<?php echo $this->url('dog/dog', ['action' => 'update','uuid' => $dog['UUID']]); ?>"><?=$dog['NAME']?></a></td>
    		</tr>
		<?php endforeach; ?>
    	</tbody>
    </table>
    
</div>