<div class="col">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Licenses</h3>
			</div>
			<div class="d-flex justify-content-end">
				<a href="" class="btn btn-primary btn-rounded mb-4" data-toggle="modal" data-target="#modalLicenseForm">Renew License</a>
			</div>
		</div>
	</div>
	
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>Tag Number</th>
    			<th>Year</th>
    			<th>Status</th>
    			<th />
    		</tr>
    	</thead>
    	<tbody>
    	<?php foreach ($this->licenses as $license) : ?>
    		<tr>
    			<td><a href="<?php echo $this->url('dog/license', ['action' => 'update','uuid' => $license['UUID']]); ?>"><?=$license['TAG']?></a></td>
    			<td><?=$license['YEAR']?></td>
    			<td><?=$license['STATUS']?></td>
    			<td>
    				<a href="<?=$this->url('dog/license', ['action' => 'delete', 'uuid' => $license['UUID']])?>" class="btn btn-danger btn-sm">&times;</a>
    			</td>
    		</tr>
		<?php endforeach; ?>
    	</tbody>
    </table>
    
</div>

<div class="modal fade" id="modalLicenseForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		<?php 
		$form = $this->form;
		$form->setAttribute('action', $this->url('dog/license', ['action' => 'create']));
		
		$form->get('DOG')->setAttributes(['value' => $this->dog]);
		
		echo $this->form()->openTag($form);
		echo $this->formCollection($form);
		echo $this->form()->closeTag($form);
		?>
		</div>
	</div>
</div>