<div class="col">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Dog Owners</h3>
			</div>
			<div class="d-flex justify-content-end">
				<a href="" class="btn btn-primary btn-rounded mb-4" data-toggle="modal" data-target="#modalDogUsersForm">Assign Owner</a>
			</div>
		</div>
	</div>
	
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>First Name</th>
    			<th>Last Name</th>
    			<th />
    		</tr>
    	</thead>
    	<tbody>
    	<?php foreach ($this->owners as $user) : ?>
    		<tr>
    			<td><a href="<?php echo $this->url('dog/owner', ['action' => 'update','uuid' => $user['UUID']]); ?>"><?=$user['FNAME']?></a></td>
    			<td><?=$user['LNAME']?></td>
    			<td>
    				<form method="POST" action="<?php echo $this->url('dog/dog', ['action' => 'unassignuser']);?>">
    					<input type="hidden" name="DOG" id="DOG" value="<?php echo $this->dog; ?>">
    					<input type="hidden" name="USER" id="USER" value="<?php echo $user['UUID']; ?>">
    					<input type="submit" name="SUBMIT" class="btn btn-danger btn-sm" id="SUBMIT" value="X">
    				</form>
    			</td>
    		</tr>
		<?php endforeach; ?>
    	</tbody>
    </table>
    
</div>

<div class="modal fade" id="modalDogUsersForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		<?php 
		$form = $this->form;
		$form->setAttribute('action', $this->url('dog/dog', ['action' => 'assignuser']));
		
		$form->get('DOG')->setAttributes(['value' => $this->dog]);
		
		echo $this->form()->openTag($form);
		echo $this->formCollection($form);
		echo $this->form()->closeTag($form);
		?>
		</div>
	</div>
</div>
