<h1>Import Dogs</h1>
<?php
$form = $this->importForm;
$form->prepare();
$form->setAttribute('action', $this->url('dog/config', ['action' => 'import']));
echo $this->form()->openTag($form); 

?>
<div class="form-group">
	<?php echo $this->formRow($form->get('SECURITY')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('FILE')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('SUBMIT')); ?>
</div>
<?php
echo $this->form()->closeTag($form);
?>
<hr>
<h1>Import Breeds</h1>
<?php
$form = $this->breedForm;
$form->prepare();
$form->setAttribute('action', $this->url('dog/config', ['action' => 'breedimport']));
echo $this->form()->openTag($form); 

?>
<div class="form-group">
	<?php echo $this->formRow($form->get('SECURITY')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('FILE')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('SUBMIT')); ?>
</div>
<?php
echo $this->form()->closeTag($form);
?>
<hr>
<h1>Clear all tables</h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('dog/config', ['action' => 'clear']));
echo $this->form()->openTag($form); 
?>
<div class="form-group">
	<?php echo $this->formRow($form->get('SECURITY')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('SUBMIT')->setAttribute('value', 'Clear')); ?>
</div>
<?php
echo $this->form()->closeTag($form);
?>
<hr>
<?php if ($this->data_is_writable) : ?>
Data Folder is Writable<br>
<?php else : ?>
Data Folder is Not Writable
run: chcon -R -t httpd_sys_rw_content_t dir
where dir is the directory specified<br>
<?php endif; ?>

<?php if ($this->photos_is_writable) : ?>
Data/Photos Folder is Writable<br>
<?php else : ?>
Data/Photos Folder is Not Writable
run: chcon -R -t httpd_sys_rw_content_t dir
where dir is the directory specified<br>
<?php endif; ?>
