<?php 
$title = "Update Owner";
$this->headtitle($title);

$form->setAttribute('action', $this->url('dog/owner', ['action' => 'update', 'uuid' => $this->uuid]));
$form->prepare();
?>
	<div class="row">
		<div class="col-md-6">
    		<?php echo $this->partial('dog/owner/partial/ownerform.phtml', ['title' => $title, 'form' => $form, 'uuid' => $this->uuid, 'update' => TRUE]); ?>
		</div>
		<div class="col-md-6">
    		<?php echo $this->partial('dog/partial/dogs.phtml', ['dogs' => $this->dogs]); ?>
		</div>
	</div>
<?php echo $this->annotations()->setAnnotations($annotations)->render(); ?>