<?php 
$title = "Update Owner";
$this->headtitle($title);

$form->setAttribute('action', $this->url('dog/owner', ['action' => 'update', 'uuid' => $this->uuid]));
$form->prepare();
?>
<div class="container">
	<div class="row">
<?php echo $this->partial('user/partial/userform.phtml', ['title' => $title, 'form' => $form, 'uuid' => $this->uuid, 'update' => TRUE]); ?>
<?php echo $this->partial('dog/partial/dogs.phtml', ['dogs' => $this->dogs]); ?>
	</div>
</div>
<?php echo $this->annotations()->setAnnotations($annotations)->render(); ?>