<?php
use Zend\Form\Element\Select;
use Zend\Form\Form;
use Dog\Model\DogModel;
?>
<div class="container">
	<?php if (count($this->dogs)) : ?>
	<table class="table table-striped">
	<thead>
		<tr>
			<th>Dog Name</th>
			<th>Breed</th>
			<th>Sex</th>
			<th>Description</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->dogs as $dog) : ?>
		<tr>
			<td>
				<?php $url = $this->url('dog/dog',['action' => 'update','uuid' => $dog['UUID']]); ?>
				<a href="<?php echo $url; ?>"><?php echo $dog['NAME']; ?></a>
			</td>
			<td><?php echo $dog['BREED']; ?></td>
			<td><?php echo DogModel::getGenderDescription($dog['SEX']); ?></td>
			<td><?php echo $dog['DESCRIPTION']; ?></td>
			<td><a href="<?php echo $this->url('dog/dog', ['action' => 'delete', 'uuid' => $dog['UUID']]); ?>">X</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
	<?php endif; ?>
	<?php echo $this->paginationControl($this->dogs, 'Sliding', '/dog/partial/paginator.phtml', ['count' => $this->count]) ?>
</div>