<div class="container">
	<table class="table table-striped">
	<thead>
		<tr>
			<th>Breed Name</th>
			<th>Status</th>
			<th>Date Created</th>
			<th>Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->breeds as $breed) : ?>
		<tr>
			<td>
				<?php $url = $this->url('dog/breed',['action' => 'update','uuid' => $breed['UUID']]); ?>
				<a href="<?php echo $url; ?>"><?php echo $breed['BREED']; ?></a>
			</td>
			<td><?php echo $breed['STATUS']; ?></td>
			<td><?php echo $breed['DATE_CREATED']; ?></td>
			<td><?php echo $breed['DATE_MODIFIED']; ?></td>
			<td><a href="<?php echo $this->url('dog/breed', ['action' => 'delete', 'uuid' => $breed['UUID']]); ?>">X</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
	</table>
	<?php echo $this->paginationControl($this->breeds, 'Sliding', '/dog/partial/paginator.phtml', ['count' => $this->count]) ?>
</div>