<?php use Dog\Model\DogModel; ?>
<div class="container border" style="width: 800px; height: 400px; font-size: 14px;">
	<div id="watermark"></div>
    <div class="row">
    	<div class="col d-flex justify-content-left">July 1, 2019 - June 30, 2020</div>
    	<div class="col d-flex justify-content-center"><h4>Dog License</h4></div>
    	<div class="col d-flex justify-content-end"><h6>TAG: <?=$this->license->TAG?></h6></div>
    </div>
    
    <div class="d-flex justify-content-center"><h6>Middletown, Connecticut</h6></div>
    <div class="row">
    	<div class="col">
    		Issued to: <?=$this->owners[0]['LNAME']?>, <?=$this->owners[0]['FNAME']?><br>
    		Address: <?=$this->owners[0]['ADDR1']?><br>
    		Phone: <?=$this->owners[0]['PHONE']?>
    	</div>
    	<div class="col">
    		Date Issued: <?=$this->license->DATE_CREATED?><br>
    		Fee: <?=$this->license->FEE?><br>
    		Codes: 
    		<?php 
    		foreach ($this->codes as $code) {
    		    echo $code['CODE'] . ":&nbsp;" . $code['DESCRIPTION'] . "<BR>";
    		}
    		?>
    	</div>
    </div>
    <hr>
    <div class="row">
    	<div class="col">
    		Dog's Name: <?=$this->dog->NAME?><br>
    		Breed: <?=$this->dog->BREED?><br>
    		Rabies Expiration Date: <?=$this->dog->DATE_RABIESEXP?>
    	</div>
    	<div class="col">
    		Description: <?=$this->dog->DESCRIPTION?><br>
    		Sex: 
    		<?php 
    		switch ($this->dog->SEX) {
    		    case DogModel::MALE:
    		        echo "Male<BR>";
    		        break;
    		    case DogModel::FEMALE:
    		        echo "FEMALE<BR>";
    		        break;
    		    case DogModel::NEUTERED:
    		        echo "Neutered<BR>";
    		        break;
    		    case DogModel::SPAYED:
    		        echo "Spayed<BR>";
    		        break;
    		}
    		?>
    	</div>
    </div>
    <hr>
    <div class="d-flex justify-content-center">
    	<p><small>Any owner or keeper applying for a license for a dog under subsection (a) of this section, except for those owners or keepers possessing a rabies vaccination exemption certificate, or a copy thereof, issued pursuant to section 22-339b, shall submit to the town clerk a rabies certificate signed by a licensed veterinarian... Per &sect; 22-338 (b).</small></p>
    </div>
    <div class="row">
    	<div class="col">
    		<p><small>This is your Dog License. Carefully perserve it.</small></p>
    	</div>
    	<div class="col">
    		Signed: Ashley A. Flynn - Town Clerk
    	</div>
    </div>
</div>