<style type="text/css" media="screen, print">
    @page
    {
        size: auto;
        margin: 25px;
       
    }
    
    .card {
        width: 450px; height: 600px; font-size: 14px;
        margin: 25px 15px 25px 40px;
    }
    
    .rotate {
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        transform: rotate(90deg);
        position: relative; top: 400px;
    }
    
    .notice {
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        transform: rotate(90deg);
        position: relative; top: 210px; right: 260px;
        width: 580px;
    }
    
    .pagebreak { page-break-after: always; }

</style>
<?php 
$max = sizeof($data);

?>
<?php for ($i=0; $i < $max; $i++) : ?>
<div class="row">
    <div class="border card">
    	<address class="rotate">
    	<?=$data[$i]['FNAME']?> <?=$data[$i]['LNAME']?><br>
    	<?=$data[$i]['ADDR1']?><br>
    	<?=$data[$i]['CITY']?> <?=$data[$i]['STATE']?>, <?=$data[$i]['ZIP']?><br>
    	</address>
    	<div class="notice" style="font-size: 10px;">2023 Dog Permit Notifications will be going paperless.  Please register your email address with the Town Clerk or Animal Control Office at the Police Department.</div>
    	<div class="notice" style="top: 350px; right: 275px;">Email Address:_____________________________________________________</div>
    </div>
    <?php $i++; ?>
    <div class="border card">
    	<address class="rotate">
    	<?=$data[$i]['FNAME']?> <?=$data[$i]['LNAME']?><br>
    	<?=$data[$i]['ADDR1']?><br>
    	<?=$data[$i]['CITY']?> <?=$data[$i]['STATE']?>, <?=$data[$i]['ZIP']?><br>
    	</address>
    	<div class="notice" style="font-size: 10px;">2023 Dog Permit Notifications will be going paperless.  Please register your email address with the Town Clerk or Animal Control Office at the Police Department.</div>
    	<div class="notice" style="top: 350px; right: 275px;">Email Address:_____________________________________________________</div>
    </div>
</div>
<div class="row pagebreak">
	<?php $i++; ?>
    <div class="border card">
    	<address class="rotate">
    	<?=$data[$i]['FNAME']?> <?=$data[$i]['LNAME']?><br>
    	<?=$data[$i]['ADDR1']?><br>
    	<?=$data[$i]['CITY']?> <?=$data[$i]['STATE']?>, <?=$data[$i]['ZIP']?><br>
    	</address>
    	<div class="notice" style="font-size: 10px;">2023 Dog Permit Notifications will be going paperless.  Please register your email address with the Town Clerk or Animal Control Office at the Police Department.</div>
    	<div class="notice" style="top: 350px; right: 275px;">Email Address:_____________________________________________________</div>
    </div>
    <?php $i++; ?>
    <div class="border card">
    	<address class="rotate">
    	<?=$data[$i]['FNAME']?> <?=$data[$i]['LNAME']?><br>
    	<?=$data[$i]['ADDR1']?><br>
    	<?=$data[$i]['CITY']?> <?=$data[$i]['STATE']?>, <?=$data[$i]['ZIP']?><br>
    	</address>
    	<div class="notice" style="font-size: 10px;">2023 Dog Permit Notifications will be going paperless.  Please register your email address with the Town Clerk or Animal Control Office at the Police Department.</div>
    	<div class="notice" style="top: 350px; right: 275px;">Email Address:_____________________________________________________</div>
    </div>
</div>
<!-- <div class="pagebreak">&nbsp;</div> -->
<?php endfor; ?>