<?php 
$title = "Update License";
$this->headtitle($title);

$form->setAttribute('action', $this->url('dog/license', ['action' => 'update', 'uuid' => $this->uuid]));
$form->prepare();
?>

<div class="container">
	<div class="row">
		<div class="col">
			<?php echo $this->partial('dog/partial/licenseform.phtml', ['title' => $title, 'form' => $form, 'uuid' => $this->uuid, 'update' => TRUE]); ?>
			<p><small>Suggested License Fee: <?=$this->license_fee?></small></p>
			<?php echo $this->partial('dog/partial/license_codes.phtml', ['title' => "Codes", 'license_uuid' => $this->uuid, 'codes' => $this->codes, 'form' => $this->codes_form]); ?>
		</div>
		<div class="col">
			<?php echo $this->partial('dog/partial/owners.phtml', ['owners' => $this->owners, 'form' => $this->owners_form, 'dog' => $this->dog['UUID']]); ?>
			<?php echo $this->partial('dog/partial/dogform.phtml', ['title' => 'Dog', 'form' => $this->dog_form, 'uuid' => $this->dog['UUID'], 'update' => TRUE]); ?>
		</div>
	</div>
</div>